name: Android CI
on: [push]
jobs:
  testing:
    name: Lint Check and Testing
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run ktlint
      run: ./gradlew spotlessCheck
    - name: Run instrumentation test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 18
        script: ./gradlew connectedCheck